-- MySQL Script generated by MySQL Workbench
-- Mon Apr  6 12:29:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema INH
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `INH` DEFAULT CHARACTER SET utf8mb4 ;
USE `INH` ;

-- -----------------------------------------------------
-- Table `INH`.`Programmes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Programmes`;
CREATE TABLE IF NOT EXISTS `INH`.`Programmes` (
  `idProgramme` INT NOT NULL,
  `Degree` VARCHAR(45) NOT NULL,
  `ProgrammeName` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(200) NOT NULL,
  `Language` VARCHAR(45) NOT NULL,
  `Duration` INT NOT NULL,
  `ProgrammeLocation` VARCHAR(45) NOT NULL,
  `TuitionFee` INT NULL,
  PRIMARY KEY (`idProgramme`))
ENGINE = InnoDB;

set autocommit=0;
INSERT INTO `Programmes` VALUES (32483 , "Bachelor" , "Political Science" , "All things politics." , "English", 4 , "Amsterdam" , 2081);
commit;



-- -----------------------------------------------------
-- Table `INH`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Students`;
CREATE TABLE IF NOT EXISTS `INH`.`Students` (
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `StudentNumber` INT NOT NULL,
  `Programme` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `PostalCode` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Counselor` INT NULL,
  `StartYear` DATE NOT NULL,
  `Gender` ENUM('M', 'F') NOT NULL,
  `ProgrammeID` INT NOT NULL,
  PRIMARY KEY (`StudentNumber`),
  INDEX `idProgramme_idx` (`ProgrammeID` ASC) VISIBLE,
  CONSTRAINT `idProgramme`
    FOREIGN KEY (`ProgrammeID`)
    REFERENCES `INH`.`Programmes` (`idProgramme`))
ENGINE = InnoDB;


set autocommit=0;
INSERT INTO `Students` VALUES ("Max" , "Musterman" , 223432 , "Political Science" , "Musterstrasse 32" , "1998-08-09" , "1234AB" , "Musterstadt" , "max@mail.com" , NULL , "2018-08-09" , "M" , 32483);
INSERT INTO `Students` VALUES ("Maria" , "Navarro" , 223842 , "Political Science" , "This Street 12" , "1999-04-02" , "0238AJ" , "Rotterdam" , "maria32@mail.com" , NULL , "2018-08-09" , "F" , 32483);
commit;


-- -----------------------------------------------------
-- Table `INH`.`Employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employees`;
CREATE TABLE IF NOT EXISTS `INH`.`Employees` (
  `idEmployees` INT NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Department` VARCHAR(45) NOT NULL,
  `Salary` INT NULL,
  `FromDate` DATE NOT NULL,
  `ToDate` DATE NULL,
  `DateOfBirth` DATE NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `PostalCode` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Gender` ENUM('F', 'M') NOT NULL,
  `Counselor` INT NULL,
  PRIMARY KEY (`idEmployees`))
ENGINE = InnoDB;

set autocommit=0;
INSERT INTO `Employees` VALUES (3213213 , "Amy" , "Whinehouse" , "Dr." , "Social Sciences" , 55000 , "1998-08-09" , NULL , "1954-04-20" , "That Street 81" , "92183JS" , "Amsterdam" , "amy@uni.edu" , "F" , NULL);
commit;

-- -----------------------------------------------------
-- Table `INH`.`Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Courses`;
CREATE TABLE IF NOT EXISTS `INH`.`Courses` (
  `CourseName` VARCHAR(45) NOT NULL,
  `Programme` INT NOT NULL,
  `Description` VARCHAR(200),
  `LECTURER` INT NOT NULL,
  `ECTS` INT NOT NULL,
  PRIMARY KEY (`CourseName`),
  INDEX `idEmployees_idx` (`LECTURER` ASC) VISIBLE,
  INDEX `idProgramme_idx` (`Programme` ASC) VISIBLE,
  CONSTRAINT `idEmployees`
    FOREIGN KEY (`LECTURER`)
    REFERENCES `INH`.`Employees` (`idEmployees`))
ENGINE = InnoDB;

set autocommit=0;
INSERT INTO `Courses` VALUES ("Sociology" , 32483 , "An informative desc" , 3213213 , 5);
commit;




-- -----------------------------------------------------
-- Table `INH`.`Exams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exams`;
CREATE TABLE IF NOT EXISTS `INH`.`Exams` (
  `Course` VARCHAR(45) NOT NULL,
  `Room` VARCHAR(45) NOT NULL,
  `Resit` ENUM('Y', 'N') NULL,
  `Date` DATE NOT NULL,
  `Time` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Course`),
  CONSTRAINT `CourseName`
    FOREIGN KEY (`Course`)
    REFERENCES `INH`.`Courses` (`CourseName`))
ENGINE = InnoDB;

set autocommit=0;
INSERT INTO `Exams` VALUES("Sociology" , "A243" , "Y" , "2018-08-09" , "12:00" );
commit;


-- -----------------------------------------------------
-- Table `INH`.`Results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Results`;
CREATE TABLE IF NOT EXISTS `INH`.`Results` (
  `Exam` VARCHAR(45) NOT NULL,
  `STUDENT` INT NOT NULL,
  `PASSED` ENUM('Y', 'N') NOT NULL,
  PRIMARY KEY (`Exam`),
  INDEX `StudentNummer_idx` (`STUDENT` ASC) VISIBLE,
  CONSTRAINT `StudentNummer`
    FOREIGN KEY (`STUDENT`)
    REFERENCES `INH`.`Students` (`StudentNumber`),
  CONSTRAINT `Course`
    FOREIGN KEY (`Exam`)
    REFERENCES `INH`.`Exams` (`Course`))
ENGINE = InnoDB;

set autocommit=0;
INSERT INTO `Results` VALUES ("Socialogy" , 223432 ,"Y" );
commit;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
