-- MySQL Script generated by MySQL Workbench
-- Mon Apr 20 11:24:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema inh
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inh` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `inh` ;

-- -----------------------------------------------------
-- Table `inh`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inh`.`employees` (
  `idEmployees` INT NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Department` VARCHAR(45) NOT NULL,
  `Salary` INT NULL DEFAULT NULL,
  `FromDate` DATE NOT NULL,
  `ToDate` DATE NULL DEFAULT NULL,
  `DateOfBirth` DATE NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `PostalCode` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Gender` ENUM('F', 'M') NOT NULL,
  `Counselor` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idEmployees`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inh`.`programmes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inh`.`programmes` (
  `idProgramme` INT NOT NULL,
  `Degree` VARCHAR(45) NOT NULL,
  `ProgrammeName` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(200) NOT NULL,
  `Language` VARCHAR(45) NOT NULL,
  `Duration` INT NOT NULL,
  `ProgrammeLocation` VARCHAR(45) NOT NULL,
  `TuitionFee` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idProgramme`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inh`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inh`.`courses` (
  `CourseName` VARCHAR(45) NOT NULL,
  `Programme` INT NOT NULL,
  `Lecturer` INT NOT NULL,
  `Description` VARCHAR(200) NULL DEFAULT NULL,
  `ECTS` INT NOT NULL,
  PRIMARY KEY (`CourseName`),
  INDEX `idEmployees_idx` (`Lecturer` ASC) VISIBLE,
  INDEX `idProgramme_idx` (`Programme` ASC) VISIBLE,
  CONSTRAINT `idEmployees`
    FOREIGN KEY (`Lecturer`)
    REFERENCES `inh`.`employees` (`idEmployees`),
  CONSTRAINT `idProgramme`
    FOREIGN KEY (`Programme`)
    REFERENCES `inh`.`programmes` (`idProgramme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inh`.`exams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inh`.`exams` (
  `idExam` INT NOT NULL,
  `Course` VARCHAR(45) NOT NULL,
  `Room` VARCHAR(45) NOT NULL,
  `Resit` ENUM('Y', 'N') NULL DEFAULT NULL,
  `Date` DATE NOT NULL,
  `Time` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idExam`),
  INDEX `CourseName` (`Course` ASC) VISIBLE,
  CONSTRAINT `CourseName`
    FOREIGN KEY (`Course`)
    REFERENCES `inh`.`courses` (`CourseName`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inh`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inh`.`students` (
  `StudentNumber` INT NOT NULL,
  `ProgrammeID` INT NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Programme` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `PostalCode` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  `Counselor` VARCHAR(45) NULL DEFAULT NULL,
  `StartYear` DATE NOT NULL,
  `Gender` ENUM('M', 'F') NOT NULL,
  PRIMARY KEY (`StudentNumber`),
  INDEX `idProgramme_idx` (`ProgrammeID` ASC) VISIBLE,
  CONSTRAINT `idProgramme`
    FOREIGN KEY (`ProgrammeID`)
    REFERENCES `inh`.`programmes` (`idProgramme`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inh`.`results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inh`.`results` (
  `Exam` VARCHAR(45) NOT NULL,
  `ExamID` INT NOT NULL,
  `Student` INT NOT NULL,
  `Grade` INT NOT NULL,
  `Passed` ENUM('Y', 'N') NOT NULL,
  PRIMARY KEY (`Exam`),
  INDEX `StudentNummer_idx` (`Student` ASC) VISIBLE,
  INDEX `idExam` (`ExamID` ASC) VISIBLE,
  CONSTRAINT `idExam`
    FOREIGN KEY (`ExamID`)
    REFERENCES `inh`.`exams` (`idExam`),
  CONSTRAINT `StudentNummer`
    FOREIGN KEY (`Student`)
    REFERENCES `inh`.`students` (`StudentNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
